<?php
$deck = [
['clubs-2'=>'2',],
['clubs-3'=>'3',],
['clubs-4'=>'4',],
['clubs-5'=>'5',],
['clubs-6'=>'6',],
['clubs-7'=>'7',],
['clubs-8'=>'8',],
['clubs-9'=>'9',],
['clubs-j'=>'10',],
['clubs-q'=>'10',],
['clubs-k'=>'10',],
['clubs-a'=>'11',],

['hearts-2'=>'2',],
['hearts-3'=>'3',],
['hearts-4'=>'4',],
['hearts-5'=>'5',],
['hearts-6'=>'6',],
['hearts-7'=>'7',],
['hearts-8'=>'8',],
['hearts-9'=>'9',],
['hearts-j'=>'10',],
['hearts-q'=>'10',],
['hearts-k'=>'10',],
['hearts-a'=>'11',],

['diamonds-2'=>'2',],
['diamonds-3'=>'3',],
['diamonds-4'=>'4',],
['diamonds-5'=>'5',],
['diamonds-6'=>'6',],
['diamonds-7'=>'7',],
['diamonds-8'=>'8',],
['diamonds-9'=>'9',],
['diamonds-j'=>'10',],
['diamonds-q'=>'10',],
['diamonds-k'=>'10',],
['diamonds-a'=>'11',],

['spades-2'=>'2',],
['spades-3'=>'3',],
['spades-4'=>'4',],
['spades-5'=>'5',],
['spades-6'=>'6',],
['spades-7'=>'7',],
['spades-8'=>'8',],
['spades-9'=>'9',],
['spades-j'=>'10',],
['spades-q'=>'10',],
['spades-k'=>'10',],
['spades-a'=>'11',],

]


?>
